-- Create users
-- DROP USER Prod CASCADE;
-- DROP USER Dev CASCADE;

-- CREATE USER Prod IDENTIFIED BY password;
-- CREATE USER Dev IDENTIFIED BY password;

-- GRANT CONNECT, RESOURCE TO Prod;
-- GRANT CONNECT, RESOURCE TO Dev;

